### ISSUE TITLE
Some Notifications Are Duplicated

### ISSUE THREAD

**Issue by IAGOnGithub** [LucasGGamerM/moshidon#220]
**Description**
Some notifications in the notifications section of the app are duplicated. Refreshing the notifications section does not fix this; duplicates remain until one of them is deleted and the notifications section is refreshed.
Deleting one does not always delete the other, but it seems like duplicates that are both in view at the same time are deleted together.
Deleting one of the two notifications works as expected. However, deleting the second (provided it was not already deleted as seen in the previous paragraph) will fail because it does not exist.
I don't know exactly what criteria causes this to occur, but it has occurred often enough (between 1/4 and 1/2 of all notifications) that I feel it should be reported anyway.

**To reproduce**

1. Receive a notification
2. It sometimes appears twice within the notification list

**Does this happen in the official app?** No

**Does this issue also occur with the respective upstream release?** No, but it occurs within Megalodon

**Screenshots**

![A notification is duplicated](https://github.com/LucasGGamerM/moshidon/assets/122576313/dc0aa157-ead0-4dba-abe1-6adfb0f99c88)

**Moshidon version:** v1.2.3+fork.101

**Crash log:** N/A

**Other:** This is from the F-Droid release

**Comment by IAGOnGithub** [comment]
This issue seems to be fixed in [Megalodon](https://github.com/sk22/megalodon/issues/616) as of a couple days ago.

**Comment by LucasGGamerM** [comment]
I will merge that soon! I just haven't had the time just yet

**Comment by LucasGGamerM** [comment]
Should be fixed now

**Comment by noodlejetski** [comment]
hi, I'm still experiencing the problem on 2.3.0+fork.107, which seems to be latest stable release, and came out after this issue has been closed.
