### ISSUE TITLE
Latest nightly crashing when app is opened

### ISSUE THREAD

**Issue by NicoCharrua** [LucasGGamerM/moshidon#354]
**Describe the bug**

Nightly 2024-03-16.

When the app is opened, the feed loads for a split seconds, then the app crashes.

**To reproduce**

1. Open app
2. See crash

**Does this happen in the official app?**

> No

**Screenshots and screen recordings**

https://github.com/LucasGGamerM/moshidon/assets/55714525/483085d6-637a-4c01-8e53-fb766a2d28a8

**Version**

Moshidon version: [2.2.4+fork.104.moshinda-nightly+@2024-03-16
org.joinmastodon.android.moshinda.nightly]

**Crash log**

If you know your way around Android development tools, please consider attaching a crash log, if possible.

(I don't, sorry)

**Comment by NicoCharrua** [comment]
It's not crashing anymore, I don't know what changed

**Comment by LucasGGamerM** [comment]
Can you get the logs? They are under Settings -> About app -> Copy latest crash log

Then I can properly diagnose the problem and hopefully fix it

**Comment by NicoCharrua** [comment]
Sure :)

2.2.4+fork.104.moshinda-nightly+@2024-03-16 (104)
2024-03-17T10:32:29.799Z

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at org.joinmastodon.android.ui.text.LinkSpan.getText(LinkSpan.java:67)
	at org.joinmastodon.android.ui.text.ClickableLinksDelegate$LinkGestureListener.onLongPress(ClickableLinksDelegate.java:119)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:894)
	at android.view.GestureDetector.-$$Nest$mdispatchLongPress(Unknown Source:0)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:326)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by NicoCharrua** [comment]
Oh wait, I think it also crashed when I long pressed a hashtag, so this crash log is for that instead?

**Comment by FineFindus** [comment]
Yes

**Comment by NicoCharrua** [comment]
It started happening again. Setting my phone to plane mode stopped the crash so I could get the crash log.

2.2.4+fork.104.moshinda-nightly+@2024-03-16 (104)
2024-03-17T14:24:37.849Z

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.joinmastodon.android.model.Mention.hashCode(Mention.java:37)
	at java.util.HashMap.hash(HashMap.java:336)
	at java.util.HashMap.put(HashMap.java:608)
	at java.util.HashSet.add(HashSet.java:220)
	at j$.util.stream.DistinctOps$1$2.accept(Unknown Source:10)
	at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(SourceFile:0)
	at j$.util.stream.AbstractPipeline.copyInto(SourceFile:0)
	at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
	at j$.util.stream.Node$-CC.evaluateSequential(Unknown Source:4)
	at j$.util.stream.AbstractPipeline.evaluate(SourceFile:0)
	at j$.util.stream.ReferencePipeline.collect(SourceFile:0)
	at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:117)
	at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:79)
	at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.buildItems(StatusDisplayItem.java:268)
	at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:64)
	at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:49)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onAppendItems(BaseStatusListFragment.java:152)
	at me.grishka.appkit.utils.Preloader.onDataLoaded(Preloader.java:86)
	at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(BaseRecyclerFragment.java:331)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onDataLoaded(BaseStatusListFragment.java:1107)
	at org.joinmastodon.android.fragments.CustomLocalTimelineFragment$1.onSuccess(CustomLocalTimelineFragment.java:63)
	at org.joinmastodon.android.fragments.CustomLocalTimelineFragment$1.onSuccess(CustomLocalTimelineFragment.java:50)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by LucasGGamerM** [comment]
Thank you for the logs. It seems like a bunch of people are experiencing the same crash for the same reason. Today's nightly should have a fix for it

**Comment by LucasGGamerM** [comment]
Fixed with c73fa2dd6bc80014738881817e03272261354f31

**Comment by NicoCharrua** [comment]
Still crashing on

2.2.4+fork.104.moshinda-nightly+@2024-03-19 (104)
2024-03-20T10:45:22.042Z

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.joinmastodon.android.model.Mention.hashCode(Mention.java:37)
	at java.util.HashMap.hash(HashMap.java:336)
	at java.util.HashMap.put(HashMap.java:608)
	at java.util.HashSet.add(HashSet.java:220)
	at j$.util.stream.DistinctOps$1$2.accept(Unknown Source:10)
	at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(SourceFile:0)
	at j$.util.stream.AbstractPipeline.copyInto(SourceFile:0)
	at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
	at j$.util.stream.Node$-CC.evaluateSequential(Unknown Source:4)
	at j$.util.stream.AbstractPipeline.evaluate(SourceFile:0)
	at j$.util.stream.ReferencePipeline.collect(SourceFile:0)
	at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:117)
	at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:79)
	at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.buildItems(StatusDisplayItem.java:268)
	at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:64)
	at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:49)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onAppendItems(BaseStatusListFragment.java:152)
	at me.grishka.appkit.utils.Preloader.onDataLoaded(Preloader.java:86)
	at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(BaseRecyclerFragment.java:331)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onDataLoaded(BaseStatusListFragment.java:1107)
	at org.joinmastodon.android.fragments.CustomLocalTimelineFragment$1.onSuccess(CustomLocalTimelineFragment.java:63)
	at org.joinmastodon.android.fragments.CustomLocalTimelineFragment$1.onSuccess(CustomLocalTimelineFragment.java:50)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by NicoCharrua** [comment]
Still crashing on latest nightly. Not sure if you'll see this after issue's closed so I'll ping @LucasGGamerM . thanks

2.2.4+fork.104.moshinda-nightly+@2024-03-21 (104)
2024-03-22T11:40:47.924Z

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.joinmastodon.android.model.Mention.hashCode(Mention.java:37)
	at java.util.HashMap.hash(HashMap.java:336)
	at java.util.HashMap.put(HashMap.java:608)
	at java.util.HashSet.add(HashSet.java:220)
	at j$.util.stream.DistinctOps$1$2.accept(Unknown Source:10)
	at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(SourceFile:0)
	at j$.util.stream.AbstractPipeline.copyInto(SourceFile:0)
	at j$.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source:10)
	at j$.util.stream.Node$-CC.evaluateSequential(Unknown Source:4)
	at j$.util.stream.AbstractPipeline.evaluate(SourceFile:0)
	at j$.util.stream.ReferencePipeline.collect(SourceFile:0)
	at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:117)
	at org.joinmastodon.android.ui.text.HtmlParser.parse(HtmlParser.java:79)
	at org.joinmastodon.android.ui.displayitems.StatusDisplayItem.buildItems(StatusDisplayItem.java:268)
	at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:64)
	at org.joinmastodon.android.fragments.StatusListFragment.buildDisplayItems(StatusListFragment.java:49)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onAppendItems(BaseStatusListFragment.java:152)
	at me.grishka.appkit.utils.Preloader.onDataLoaded(Preloader.java:86)
	at me.grishka.appkit.fragments.BaseRecyclerFragment.onDataLoaded(BaseRecyclerFragment.java:331)
	at org.joinmastodon.android.fragments.BaseStatusListFragment.onDataLoaded(BaseStatusListFragment.java:1107)
	at org.joinmastodon.android.fragments.CustomLocalTimelineFragment$1.onSuccess(CustomLocalTimelineFragment.java:63)
	at org.joinmastodon.android.fragments.CustomLocalTimelineFragment$1.onSuccess(CustomLocalTimelineFragment.java:50)
	at me.grishka.appkit.api.APIRequest$1.run(APIRequest.java:29)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by LucasGGamerM** [comment]
This one is a different crash, which I forgot to fix yesterday

**Comment by LucasGGamerM** [comment]
Fixed with 629262c266f32809d8fcde6306013d34eb49211a
